name: Meetup Proposal
description: Describe your proposal for a presentation at the Blockchain CoP.
title: 'Meetup Proposal - '
body:
  - type: input
    attributes:
      label: Title
      description: The title of your presentation.
      placeholder: Presentation Title
  - type: input
    attributes:
      label: Description
      description: Please provide a brief description (2-3 sentences) of your proposal, along with any details of your talk.
      placeholder: Presentation Description
