name: Meetup Proposal
description: Describe your proposal for a presentation at the Blockchain CoP.
title: 'Meetup Proposal - '
body:
  - type: input
    id: title
    validations:
      required: true
    attributes:
      label: Title
      description: The title of your presentation.
      placeholder: Presentation Title
  - type: input
    id: position
    validations:
      required: false
    attributes:
      label: Position
      description: Your current job position or academic status
      placeholder: E.g. Blockchain Engineer at Coinbase
  - type: input
    id: organization
    validations:
      required: false
    attributes:
      label: Organization
      description: Your current organization that this presentation is related to, if any.
      placeholder: E.g. Protocol Labs
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: Please provide a brief description (2-3 sentences) of your proposal, along with any details of your talk.
      placeholder: Presentation Description
  - type: textarea
    id: resources
    validations:
      required: false
    attributes:
      label: Resources
      description: If you would like to include any additional resources for the audience, please include them here.
      placeholder: Resources
  - type: input
    id: date
    attributes:
      label: Presentation Date
      description: |
        Blockchain CoP meetups occur on Tuesdays at 11AM EDT.
        Please provide the date on which your talk is scheduled for.
      placeholder: day/month
  - type: textarea
    id: contact
    validations:
      required: false
    attributes:
      label: Contact Info
      description: |
        Please include any email addresses or social media links here if you would 
        like people to contact you through them.
      placeholder: |
        - Email: bob@example.com
        - Twitter: @handle